//! Integration tests using real data fixtures collected from an acki-nacki node.
//!
//! Fixture JSON files are generated by `dex-circuit-data-exporter` (in acki-nacki/helpers/)
//! and placed in `tests/fixtures/dex_fixture*.json`.
//!
//! Tests are skipped gracefully if no fixture files are found.
//!
//! # Running
//! ```bash
//! # MockProver (fast)
//! cargo test test_real_data_mock_prover -- --nocapture
//!
//! # Real prover (proves one VK works for all fixtures)
//! cargo test --release test_real_data_real_prover -- --nocapture
//! ```

use gosh_dark_dex_halo2_new_circuit::boc_helper::{serialize_cells_tree_root_first, BocFlattenData};
use gosh_dark_dex_halo2_new_circuit::dark_dex_circuit_new::DarkDexCircuitNew;
use gosh_dark_dex_halo2_new_circuit::poseidon::poseidon_hash;

use gosh_dense_balanced_tree::{
    bytes_to_fr, compute_root_native, fr_to_bytes, preprocess_dense_proof,
    DenseChainLink, MAX_CHAIN_LEN,
};
use halo2_base::gates::circuit::BaseCircuitParams;
use halo2_base::halo2_proofs::dev::MockProver;
use halo2_base::halo2_proofs::halo2curves::bn256::Fr;
use halo2_base::halo2_proofs::halo2curves::ff::PrimeField;
use serde::Deserialize;
use tvm_block::{Deserializable, Message, Serializable};

const K: u32 = 19;

fn base_circuit_params() -> BaseCircuitParams {
    BaseCircuitParams {
        k: K as usize,
        num_advice_per_phase: vec![4],
        num_fixed: 1,
        num_lookup_advice_per_phase: vec![1],
        lookup_bits: Some(18),
        num_instance_columns: 1,
    }
}

// ---------------------------------------------------------------------------
// JSON fixture structures
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct ChainLinkJson {
    active: bool,
    siblings_hex: Vec<String>,
    position: usize,
    leaf_hex: String,
}

#[derive(Deserialize)]
struct DexFixtureJson {
    #[allow(dead_code)]
    description: String,
    sk_u_hex: String,
    event_boc_base64: String,
    events_proof_siblings_hex: Vec<String>,
    events_proof_position: usize,
    account_dapp_id_hex: String,
    account_id_hex: String,
    block_id_hex: String,
    envelope_hash_hex: String,
    block_proof_siblings_hex: Vec<String>,
    block_proof_position: usize,
    num_active_chain_steps: usize,
    dense_chain: Vec<ChainLinkJson>,
}

// ---------------------------------------------------------------------------
// Fixture loading & parsing
// ---------------------------------------------------------------------------

fn discover_fixtures() -> Vec<std::path::PathBuf> {
    let fixtures_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    if !fixtures_dir.exists() {
        return vec![];
    }
    let mut paths: Vec<_> = std::fs::read_dir(&fixtures_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with("dex_fixture") && n.ends_with(".json"))
                .unwrap_or(false)
        })
        .collect();
    paths.sort();
    paths
}

fn load_fixture(path: &std::path::Path) -> DexFixtureJson {
    let content = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Failed to read fixture {}: {}", path.display(), e));
    serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Failed to parse fixture {}: {}", path.display(), e))
}

fn hex_to_32(hex_str: &str) -> [u8; 32] {
    let bytes = hex::decode(hex_str).expect("invalid hex string");
    assert_eq!(bytes.len(), 32, "expected 32-byte hex value, got {}", bytes.len());
    bytes.try_into().unwrap()
}

fn hex_to_fr(hex_str: &str) -> Fr {
    let bytes = hex_to_32(hex_str);
    Fr::from_repr(bytes).expect("hex value is not a valid Fr element")
}

/// Big-endian byte-to-Fr conversion for BOC field extraction.
fn bytes_to_fr_be(data: &[u8]) -> Fr {
    let mut val = Fr::from(0u64);
    for &byte in data.iter() {
        val = val * Fr::from(256u64) + Fr::from(byte as u64);
    }
    val
}

/// Event field byte offsets in the child cell's cell_repr_data.
const EVENT_SK_U_COMMIT_START: usize = 6;
const EVENT_SK_U_COMMIT_END: usize = 38;
const EVENT_VOUCHER_NOMINAL_START: usize = 38;
const EVENT_VOUCHER_NOMINAL_END: usize = 70;
const EVENT_TOKEN_TYPE_START: usize = 70;
const EVENT_TOKEN_TYPE_END: usize = 74;

struct ParsedFixture {
    sk_u: Fr,
    entries: [BocFlattenData; 2],
    events_proof_siblings: Vec<[u8; 32]>,
    events_proof_position: usize,
    account_dapp_id: [u8; 32],
    account_id: [u8; 32],
    block_id: [u8; 32],
    envelope_hash_bytes: [u8; 32],
    block_proof_siblings: Vec<[u8; 32]>,
    block_proof_position: usize,
    dense_chain: Vec<DenseChainLink>,
    num_active_chain_steps: usize,
}

fn parse_fixture(json: &DexFixtureJson) -> ParsedFixture {
    // Parse sk_u
    let sk_u = hex_to_fr(&json.sk_u_hex);

    // Parse BOC
    let msg = Message::construct_from_base64(&json.event_boc_base64)
        .expect("Failed to parse event BOC");
    let msg_cell = msg.serialize().expect("Failed to serialize message");
    let serialized = serialize_cells_tree_root_first(&msg_cell)
        .expect("Failed to flatten BOC");
    assert_eq!(serialized.len(), 2, "Expected exactly 2 cells in event BOC");
    let entries: [BocFlattenData; 2] = [serialized[0].clone(), serialized[1].clone()];

    // Parse events proof
    let events_proof_siblings: Vec<[u8; 32]> = json
        .events_proof_siblings_hex
        .iter()
        .map(|s| hex_to_32(s))
        .collect();

    // Parse block proof
    let block_proof_siblings: Vec<[u8; 32]> = json
        .block_proof_siblings_hex
        .iter()
        .map(|s| hex_to_32(s))
        .collect();

    // Parse dense chain
    let mut dense_chain: Vec<DenseChainLink> = json
        .dense_chain
        .iter()
        .map(|link| {
            let siblings: Vec<[u8; 32]> =
                link.siblings_hex.iter().map(|s| hex_to_32(s)).collect();
            DenseChainLink {
                active: link.active,
                siblings,
                position: link.position,
                leaf_native: hex_to_32(&link.leaf_hex),
            }
        })
        .collect();

    // Ensure chain is exactly MAX_CHAIN_LEN.
    // Inactive (padding) links must have leaf_native = fr_to_bytes(current_root)
    // where current_root is the Merkle root after all active chain steps.
    // This is because the circuit passes `current` (an AssignedValue) as the leaf
    // for each link, and inactive links keep `current` unchanged via gate.select.
    // The chunk decomposition constraints inside dense_merkle_root_circuit still
    // run on every link, so the preprocess witnesses must match `current`.
    assert!(
        dense_chain.len() <= MAX_CHAIN_LEN,
        "Dense chain too long: {} > {}",
        dense_chain.len(),
        MAX_CHAIN_LEN
    );

    if dense_chain.len() < MAX_CHAIN_LEN {
        // Compute root_1 (block tree root) to determine the correct padding leaf.
        let repr_hash = &entries[0].repr_hash;
        let ext_msg_leaf = poseidon_hash_96_native(
            &hex_to_32(&json.account_dapp_id_hex),
            &hex_to_32(&json.account_id_hex),
            repr_hash,
        );
        let ext_out_root_bytes = if events_proof_siblings.is_empty() {
            ext_msg_leaf
        } else {
            let events_proof = preprocess_dense_proof(
                ext_msg_leaf,
                &events_proof_siblings,
                json.events_proof_position,
            );
            fr_to_bytes(compute_root_native(&events_proof))
        };
        let block_leaf = poseidon_hash_96_native(
            &hex_to_32(&json.block_id_hex),
            &hex_to_32(&json.envelope_hash_hex),
            &ext_out_root_bytes,
        );
        let block_proof = preprocess_dense_proof(
            block_leaf,
            &block_proof_siblings,
            json.block_proof_position,
        );
        let root_1_fr = compute_root_native(&block_proof);

        // Walk the active chain steps to compute the current root.
        let mut current = root_1_fr;
        for link in dense_chain.iter().filter(|l| l.active) {
            let proof = preprocess_dense_proof(
                link.leaf_native,
                &link.siblings,
                link.position,
            );
            current = compute_root_native(&proof);
        }

        let padding_leaf = fr_to_bytes(current);
        let depth = if !dense_chain.is_empty() {
            dense_chain[0].siblings.len()
        } else {
            block_proof_siblings.len()
        };

        while dense_chain.len() < MAX_CHAIN_LEN {
            dense_chain.push(DenseChainLink::inactive(padding_leaf, depth));
        }
    }

    ParsedFixture {
        sk_u,
        entries,
        events_proof_siblings,
        events_proof_position: json.events_proof_position,
        account_dapp_id: hex_to_32(&json.account_dapp_id_hex),
        account_id: hex_to_32(&json.account_id_hex),
        block_id: hex_to_32(&json.block_id_hex),
        envelope_hash_bytes: hex_to_32(&json.envelope_hash_hex),
        block_proof_siblings,
        block_proof_position: json.block_proof_position,
        dense_chain,
        num_active_chain_steps: json.num_active_chain_steps,
    }
}

/// Compute the two public instances for the circuit.
///
/// Returns `[poseidon_commitment, final_root]`.
fn compute_instances(parsed: &ParsedFixture) -> Vec<Fr> {
    // Instance 1: Poseidon(voucher_nominal, token_type, sk_u, sk_u_commit)
    let child_data = &parsed.entries[1].cell_repr_data;

    let sk_u_commit_bytes: [u8; 32] = child_data[EVENT_SK_U_COMMIT_START..EVENT_SK_U_COMMIT_END]
        .try_into()
        .unwrap();
    let sk_u_commit_val = Fr::from_repr(sk_u_commit_bytes).unwrap();
    let voucher_nominal_val =
        bytes_to_fr_be(&child_data[EVENT_VOUCHER_NOMINAL_START..EVENT_VOUCHER_NOMINAL_END]);
    let token_type_val =
        bytes_to_fr_be(&child_data[EVENT_TOKEN_TYPE_START..EVENT_TOKEN_TYPE_END]);

    let poseidon_commitment =
        poseidon_hash(&[voucher_nominal_val, token_type_val, parsed.sk_u, sk_u_commit_val]);

    // Instance 2: final_root after chain verification
    // Compute root_1 from block proof natively, then walk the chain.
    let block_leaf_native = {
        // poseidon_hash_96_native(block_id, envelope_hash, ext_out_root)
        // But we need ext_out_root, which comes from the events proof.
        // Compute ext_msg_leaf first.
        let repr_hash = &parsed.entries[0].repr_hash;
        let ext_msg_leaf = poseidon_hash_96_native(
            &parsed.account_dapp_id,
            &parsed.account_id,
            repr_hash,
        );

        // Compute events root from proof.
        // When there are no events siblings (depth 0), the root IS the leaf.
        let ext_out_root_bytes = if parsed.events_proof_siblings.is_empty() {
            ext_msg_leaf
        } else {
            let events_proof = preprocess_dense_proof(
                ext_msg_leaf,
                &parsed.events_proof_siblings,
                parsed.events_proof_position,
            );
            let ext_out_root_fr = compute_root_native(&events_proof);
            fr_to_bytes(ext_out_root_fr)
        };

        // block_leaf = Poseidon(block_id || envelope_hash || ext_out_root)
        poseidon_hash_96_native(
            &parsed.block_id,
            &parsed.envelope_hash_bytes,
            &ext_out_root_bytes,
        )
    };

    // Compute root_1 from block proof
    let block_proof = preprocess_dense_proof(
        block_leaf_native,
        &parsed.block_proof_siblings,
        parsed.block_proof_position,
    );
    let root_1_fr = compute_root_native(&block_proof);

    // Walk the chain
    let final_root = if parsed.num_active_chain_steps == 0 {
        root_1_fr
    } else {
        let mut current = root_1_fr;
        for link in parsed.dense_chain.iter().take(parsed.num_active_chain_steps) {
            assert!(link.active);
            let leaf_bytes = fr_to_bytes(current);
            assert_eq!(
                leaf_bytes, link.leaf_native,
                "Chain link leaf mismatch"
            );
            let proof = preprocess_dense_proof(
                link.leaf_native,
                &link.siblings,
                link.position,
            );
            current = compute_root_native(&proof);
        }
        current
    };

    vec![poseidon_commitment, final_root, voucher_nominal_val, token_type_val]
}

/// Native poseidon_hash_96: hash 3 × 32-byte inputs with 31-byte chunking.
/// Must match the circuit's `poseidon_hash_96_native`.
fn poseidon_hash_96_native(a: &[u8; 32], b: &[u8; 32], c: &[u8; 32]) -> [u8; 32] {
    let mut buf = [0u8; 96];
    buf[..32].copy_from_slice(a);
    buf[32..64].copy_from_slice(b);
    buf[64..96].copy_from_slice(c);

    let chunk = |start: usize, len: usize| -> Fr {
        let mut b32 = [0u8; 32];
        b32[..len].copy_from_slice(&buf[start..start + len]);
        bytes_to_fr(&b32)
    };

    let c0 = chunk(0, 31);
    let c1 = chunk(31, 31);
    let c2 = chunk(62, 31);
    let c3 = chunk(93, 3);

    let hash = poseidon_hash(&[c0, c1, c2, c3]);
    fr_to_bytes(hash)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn test_real_data_mock_prover() {
    let fixtures = discover_fixtures();
    if fixtures.is_empty() {
        println!("No fixture files found in tests/fixtures/ — skipping test.");
        println!("Run dex-circuit-data-exporter to generate fixtures.");
        return;
    }

    let params = base_circuit_params();

    for fixture_path in &fixtures {
        let filename = fixture_path.file_name().unwrap().to_str().unwrap();
        println!("\n========== MockProver: {} ==========", filename);

        let json = load_fixture(fixture_path);
        println!("  Description: {}", json.description);
        println!("  Chain steps: {}", json.num_active_chain_steps);

        let parsed = parse_fixture(&json);
        let ephemeral_pubkey = Fr::from(0xDEADu64);
        let mut instances = compute_instances(&parsed);
        instances.push(ephemeral_pubkey);

        println!(
            "  Expected instances: poseidon={}, final_root={}",
            hex::encode(instances[0].to_repr()),
            hex::encode(instances[1].to_repr()),
        );

        let circuit = DarkDexCircuitNew::new(
            parsed.sk_u,
            ephemeral_pubkey,
            parsed.entries,
            parsed.events_proof_siblings,
            parsed.events_proof_position,
            parsed.account_dapp_id,
            parsed.account_id,
            parsed.block_id,
            parsed.envelope_hash_bytes,
            parsed.block_proof_siblings,
            parsed.block_proof_position,
            parsed.dense_chain,
            parsed.num_active_chain_steps,
            params.clone(),
        );

        println!("  Running MockProver...");
        let prover = MockProver::<Fr>::run(K, &circuit, vec![instances]).unwrap();
        match prover.verify() {
            Ok(()) => println!("  {} PASSED", filename),
            Err(errors) => {
                println!("  {} FAILED with {} errors:", filename, errors.len());
                for (i, err) in errors.iter().enumerate().take(30) {
                    println!("    Error {}: {}", i, err);
                }
                panic!("MockProver failed for {}", filename);
            }
        }
    }

    println!("\nAll {} fixture(s) passed MockProver!", fixtures.len());
}

#[test]
fn test_real_data_real_prover() {
    use halo2_base::halo2_proofs::plonk::{keygen_pk, keygen_vk};
    use halo2_base::utils::fs::gen_srs;
    use halo2_base::utils::testing::{check_proof_with_instances, gen_proof_with_instances};
    use std::time::Instant;

    let fixtures = discover_fixtures();
    if fixtures.is_empty() {
        println!("No fixture files found in tests/fixtures/ — skipping test.");
        println!("Run dex-circuit-data-exporter to generate fixtures.");
        return;
    }

    println!("Found {} fixture(s)", fixtures.len());

    let params = base_circuit_params();

    // Step 1: Keygen from the first fixture
    let first_json = load_fixture(&fixtures[0]);
    let first_parsed = parse_fixture(&first_json);

    let ephemeral_pubkey = Fr::from(0xDEADu64);
    let keygen_circuit = DarkDexCircuitNew::new(
        first_parsed.sk_u,
        ephemeral_pubkey,
        first_parsed.entries,
        first_parsed.events_proof_siblings,
        first_parsed.events_proof_position,
        first_parsed.account_dapp_id,
        first_parsed.account_id,
        first_parsed.block_id,
        first_parsed.envelope_hash_bytes,
        first_parsed.block_proof_siblings,
        first_parsed.block_proof_position,
        first_parsed.dense_chain,
        first_parsed.num_active_chain_steps,
        params.clone(),
    );

    println!("Generating SRS (K={})...", K);
    let srs = gen_srs(K);

    let start = Instant::now();
    let vk = keygen_vk(&srs, &keygen_circuit).expect("keygen_vk failed");
    println!("keygen_vk: {:?}", start.elapsed());

    let start = Instant::now();
    let pk = keygen_pk(&srs, vk, &keygen_circuit).expect("keygen_pk failed");
    println!("keygen_pk: {:?}", start.elapsed());

    let break_points = keygen_circuit.base_circuit_builder.borrow().break_points();

    // Step 2: Prove each fixture with the shared VK/PK
    struct ProofResult {
        filename: String,
        chain_steps: usize,
        prove_ms: u128,
        verify_ms: u128,
        proof_size: usize,
    }
    let mut results: Vec<ProofResult> = Vec::new();

    for fixture_path in &fixtures {
        let filename = fixture_path
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .to_string();
        println!("\n========== Real proof: {} ==========", filename);

        let json = load_fixture(fixture_path);
        println!("  Description: {}", json.description);
        let chain_steps = json.num_active_chain_steps;

        let parsed = parse_fixture(&json);
        let mut instances = compute_instances(&parsed);
        instances.push(ephemeral_pubkey);

        let prover_circuit = DarkDexCircuitNew::new_for_proving(
            parsed.sk_u,
            ephemeral_pubkey,
            parsed.entries,
            parsed.events_proof_siblings,
            parsed.events_proof_position,
            parsed.account_dapp_id,
            parsed.account_id,
            parsed.block_id,
            parsed.envelope_hash_bytes,
            parsed.block_proof_siblings,
            parsed.block_proof_position,
            parsed.dense_chain,
            parsed.num_active_chain_steps,
            params.clone(),
            break_points.clone(),
        );

        let start = Instant::now();
        let proof_bytes =
            gen_proof_with_instances(&srs, &pk, prover_circuit, &[&instances]);
        let prove_ms = start.elapsed().as_millis();
        println!("  Proof generation: {}ms ({} bytes)", prove_ms, proof_bytes.len());

        let start = Instant::now();
        check_proof_with_instances(&srs, pk.get_vk(), &proof_bytes, &[&instances], true);
        let verify_ms = start.elapsed().as_millis();
        println!("  Proof verification: {}ms", verify_ms);
        println!("  {} PASSED", filename);

        results.push(ProofResult {
            filename,
            chain_steps,
            prove_ms,
            verify_ms,
            proof_size: proof_bytes.len(),
        });
    }

    // Print summary table
    println!("\n╔════════════════════════════════════════════╤════════╤══════════╤══════════╤════════════╗");
    println!("║ fixture                                    │ steps  │  prove   │  verify  │ proof_size ║");
    println!("╠════════════════════════════════════════════╪════════╪══════════╪══════════╪════════════╣");
    for r in &results {
        println!(
            "║ {:<42} │   {:>2}   │ {:>6}ms │ {:>6}ms │   {:>6}B  ║",
            r.filename, r.chain_steps, r.prove_ms, r.verify_ms, r.proof_size,
        );
    }
    println!("╚════════════════════════════════════════════╧════════╧══════════╧══════════╧════════════╝");
    println!(
        "\nAll {} fixture(s) passed with shared VK/PK!",
        results.len()
    );
}


#[test]
fn test_debug_fixture_native() {
    let fixtures = discover_fixtures();
    if fixtures.is_empty() {
        println!("No fixtures found — skipping.");
        return;
    }

    let fixture_path = &fixtures[0];
    let filename = fixture_path.file_name().unwrap().to_str().unwrap();
    println!("\n========== Debug: {} ==========", filename);

    let json = load_fixture(fixture_path);
    let parsed = parse_fixture(&json);

    // 1. Verify BOC: SHA-256 of cell_repr_data should match repr_hash
    use sha2::{Sha256, Digest};
    let mut hasher = Sha256::new();
    hasher.update(&parsed.entries[0].cell_repr_data);
    let root_sha256: [u8; 32] = hasher.finalize().into();
    println!("  Root repr_hash from BOC: {}", hex::encode(&parsed.entries[0].repr_hash));
    println!("  Root SHA-256 of cell_repr_data: {}", hex::encode(&root_sha256));
    assert_eq!(root_sha256, parsed.entries[0].repr_hash, "Root SHA-256 mismatch!");

    let mut hasher = Sha256::new();
    hasher.update(&parsed.entries[1].cell_repr_data);
    let child_sha256: [u8; 32] = hasher.finalize().into();
    println!("  Child repr_hash from BOC: {}", hex::encode(&parsed.entries[1].repr_hash));
    println!("  Child SHA-256 of cell_repr_data: {}", hex::encode(&child_sha256));
    assert_eq!(child_sha256, parsed.entries[1].repr_hash, "Child SHA-256 mismatch!");

    // 2. Verify child hash is embedded in root cell
    let offset = parsed.entries[0].childs_repr_hashes_offset.as_ref().unwrap()[0] as usize;
    let embedded_hash = &parsed.entries[0].cell_repr_data[offset..offset+32];
    println!("  Child hash embedded in root at offset {}: {}", offset, hex::encode(embedded_hash));
    assert_eq!(embedded_hash, &parsed.entries[1].repr_hash, "Embedded child hash mismatch!");

    // 3. Check repr_hash_fr packing
    let repr_hash_fr = bytes_to_fr(&parsed.entries[0].repr_hash);
    println!("  repr_hash_fr (LE packed): {}", hex::encode(fr_to_bytes(repr_hash_fr)));

    // 4. Check ext_msg_leaf
    let ext_msg_leaf = poseidon_hash_96_native(
        &parsed.account_dapp_id,
        &parsed.account_id,
        &parsed.entries[0].repr_hash,
    );
    println!("  ext_msg_leaf: {}", hex::encode(&ext_msg_leaf));

    // 5. Check events root (should equal ext_msg_leaf for depth 0)
    let ext_out_root = if parsed.events_proof_siblings.is_empty() {
        println!("  Events depth = 0, ext_out_root = ext_msg_leaf");
        ext_msg_leaf
    } else {
        let events_proof = preprocess_dense_proof(
            ext_msg_leaf,
            &parsed.events_proof_siblings,
            parsed.events_proof_position,
        );
        let root = fr_to_bytes(compute_root_native(&events_proof));
        println!("  Events root: {}", hex::encode(&root));
        root
    };

    // 6. Check block_leaf
    let block_leaf = poseidon_hash_96_native(
        &parsed.block_id,
        &parsed.envelope_hash_bytes,
        &ext_out_root,
    );
    println!("  block_leaf: {}", hex::encode(&block_leaf));

    // 7. Check block root (root_1)
    let block_proof = preprocess_dense_proof(
        block_leaf,
        &parsed.block_proof_siblings,
        parsed.block_proof_position,
    );
    let root_1_fr = compute_root_native(&block_proof);
    let root_1_bytes = fr_to_bytes(root_1_fr);
    println!("  root_1 (block tree root): {}", hex::encode(&root_1_bytes));

    // 8. Check chain padding
    let num_active = parsed.num_active_chain_steps;
    println!("  Active chain steps: {}", num_active);
    println!("  Chain length: {}", parsed.dense_chain.len());
    for (i, link) in parsed.dense_chain.iter().enumerate().take(3) {
        println!("    chain[{}]: active={}, leaf={}, depth={}", 
                 i, link.active, hex::encode(&link.leaf_native), link.siblings.len());
    }

    // 9. Verify chain padding leaf matches root_1 (for T=0)
    if num_active == 0 {
        let padding_leaf = &parsed.dense_chain[0].leaf_native;
        println!("  Padding leaf:     {}", hex::encode(padding_leaf));
        println!("  Expected (root_1): {}", hex::encode(&root_1_bytes));
        assert_eq!(padding_leaf, &root_1_bytes, "Padding leaf should equal root_1 for T=0!");
    }

    // 10. Compute instances
    let instances = compute_instances(&parsed);
    println!("  Instance 0 (poseidon): {}", hex::encode(instances[0].to_repr()));
    println!("  Instance 1 (final_root): {}", hex::encode(instances[1].to_repr()));

    println!("\n  All native checks passed!");
}


#[test]
fn test_debug_sku_commit() {
    let fixtures = discover_fixtures();
    if fixtures.is_empty() {
        return;
    }
    let json = load_fixture(&fixtures[0]);
    let parsed = parse_fixture(&json);

    // Extract sk_u_commit from child cell
    let child_data = &parsed.entries[1].cell_repr_data;
    let sk_u_commit_bytes: [u8; 32] = child_data[EVENT_SK_U_COMMIT_START..EVENT_SK_U_COMMIT_END]
        .try_into()
        .unwrap();
    let sk_u_commit_val = Fr::from_repr(sk_u_commit_bytes).unwrap();
    
    // Compute expected sk_u_commit = Poseidon(sk_u, 0)
    let expected_commit = poseidon_hash(&[parsed.sk_u, Fr::zero()]);
    
    println!("sk_u: {}", hex::encode(parsed.sk_u.to_repr()));
    println!("sk_u_commit from BOC: {}", hex::encode(sk_u_commit_val.to_repr()));
    println!("Poseidon(sk_u, 0):    {}", hex::encode(expected_commit.to_repr()));
    assert_eq!(sk_u_commit_val, expected_commit, "sk_u_commit mismatch!");
    println!("sk_u_commit check PASSED");
}


#[test]
fn test_debug_all_fixtures_sku_commit() {
    let fixtures = discover_fixtures();
    if fixtures.is_empty() {
        return;
    }

    let p_hex = "30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001";

    println!("Found {} fixtures", fixtures.len());
    for (idx, fixture_path) in fixtures.iter().enumerate() {
        let filename = fixture_path.file_name().unwrap().to_str().unwrap();
        println!("[{}] Processing: {}", idx, filename);
        let json = load_fixture(fixture_path);
        println!("[{}] Loaded OK", idx);
        let parsed = parse_fixture(&json);
        println!("[{}] Parsed OK", idx);
        
        let child_data = &parsed.entries[1].cell_repr_data;
        let sk_u_commit_bytes: [u8; 32] = child_data[EVENT_SK_U_COMMIT_START..EVENT_SK_U_COMMIT_END]
            .try_into()
            .unwrap();
        
        println!("[{}] {}: sk_u_commit_bytes = {}", idx, filename, hex::encode(&sk_u_commit_bytes));
        
        // Check if it's a valid Fr element
        let opt: Option<Fr> = Fr::from_repr(sk_u_commit_bytes).into();
        match opt {
            Some(fr) => {
                let expected = poseidon_hash(&[parsed.sk_u, Fr::zero()]);
                let match_str = if fr == expected { "MATCH" } else { "MISMATCH" };
                println!("[{}]   Valid Fr: {} ({})", idx, hex::encode(fr.to_repr()), match_str);
            },
            None => {
                println!("[{}]   NOT a valid Fr! (exceeds modulus)", idx);
                let fr = bytes_to_fr(&sk_u_commit_bytes);
                let expected = poseidon_hash(&[parsed.sk_u, Fr::zero()]);
                let match_str = if fr == expected { "MATCH" } else { "MISMATCH" };
                println!("[{}]   bytes_to_fr: {} ({})", idx, hex::encode(fr_to_bytes(fr)), match_str);
            }
        }
    }
    println!("Done with all fixtures");
}


#[test]
fn test_focused_l1_h197() {
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/dex_fixture_L1_H197_S0.json");
    if !fixture_path.exists() {
        println!("Fixture not found — skipping.");
        return;
    }

    let json = load_fixture(&fixture_path);
    println!("Description: {}", json.description);
    println!("events_proof depth: {}", json.events_proof_siblings_hex.len());
    println!("block_proof depth: {}", json.block_proof_siblings_hex.len());
    println!("chain_steps: {}", json.num_active_chain_steps);
    println!("chain_len: {}", json.dense_chain.len());

    let parsed = parse_fixture(&json);
    println!("Parsed chain_len: {}", parsed.dense_chain.len());
    for (i, link) in parsed.dense_chain.iter().enumerate() {
        println!("  chain[{}]: active={}, leaf={}, depth={}", 
                 i, link.active, hex::encode(&link.leaf_native), link.siblings.len());
    }

    let ephemeral_pubkey = Fr::from(0xDEADu64);
    let mut instances = compute_instances(&parsed);
    instances.push(ephemeral_pubkey);
    println!("Instance 0 (poseidon): {}", hex::encode(instances[0].to_repr()));
    println!("Instance 1 (final_root): {}", hex::encode(instances[1].to_repr()));

    let params = base_circuit_params();
    let circuit = DarkDexCircuitNew::new(
        parsed.sk_u,
        ephemeral_pubkey,
        parsed.entries,
        parsed.events_proof_siblings,
        parsed.events_proof_position,
        parsed.account_dapp_id,
        parsed.account_id,
        parsed.block_id,
        parsed.envelope_hash_bytes,
        parsed.block_proof_siblings,
        parsed.block_proof_position,
        parsed.dense_chain,
        parsed.num_active_chain_steps,
        params,
    );

    println!("Running MockProver with K={}...", K);
    let prover = MockProver::<Fr>::run(K, &circuit, vec![instances]).unwrap();
    match prover.verify() {
        Ok(()) => println!("PASSED!"),
        Err(errors) => {
            println!("FAILED with {} errors:", errors.len());
            for (i, err) in errors.iter().enumerate() {
                println!("  Error {}: {}", i, err);
            }
            panic!("MockProver failed");
        }
    }
}

#[test]
fn test_focused_l0_h197() {
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/dex_fixture_L0_H197_S0.json");
    if !fixture_path.exists() {
        println!("Fixture not found — skipping.");
        return;
    }

    let json = load_fixture(&fixture_path);
    println!("Description: {}", json.description);
    println!("events_proof depth: {}", json.events_proof_siblings_hex.len());
    println!("block_proof depth: {}", json.block_proof_siblings_hex.len());
    println!("chain_steps: {}", json.num_active_chain_steps);
    println!("chain_len: {}", json.dense_chain.len());

    let parsed = parse_fixture(&json);
    println!("Parsed chain_len: {}", parsed.dense_chain.len());
    for (i, link) in parsed.dense_chain.iter().enumerate() {
        println!("  chain[{}]: active={}, leaf={}, depth={}",
                 i, link.active, hex::encode(&link.leaf_native), link.siblings.len());
    }

    let ephemeral_pubkey = Fr::from(0xDEADu64);
    let mut instances = compute_instances(&parsed);
    instances.push(ephemeral_pubkey);
    println!("Instance 0 (poseidon): {}", hex::encode(instances[0].to_repr()));
    println!("Instance 1 (final_root): {}", hex::encode(instances[1].to_repr()));

    let params = base_circuit_params();
    let circuit = DarkDexCircuitNew::new(
        parsed.sk_u,
        ephemeral_pubkey,
        parsed.entries,
        parsed.events_proof_siblings,
        parsed.events_proof_position,
        parsed.account_dapp_id,
        parsed.account_id,
        parsed.block_id,
        parsed.envelope_hash_bytes,
        parsed.block_proof_siblings,
        parsed.block_proof_position,
        parsed.dense_chain,
        parsed.num_active_chain_steps,
        params,
    );

    println!("Running MockProver with K={}...", K);
    let prover = MockProver::<Fr>::run(K, &circuit, vec![instances]).unwrap();
    match prover.verify() {
        Ok(()) => println!("PASSED!"),
        Err(errors) => {
            println!("FAILED with {} errors:", errors.len());
            for (i, err) in errors.iter().enumerate() {
                println!("  Error {}: {}", i, err);
            }
            panic!("MockProver failed");
        }
    }
}

/// Regenerate tvm-sdk's halo2 test artifacts (proof + instances .bin files)
/// for the three H197 fixtures. Gated on env var `TVM_SDK_EXPORT_DIR`; inert by default.
///
/// Requires `PARAMS_DIR` to point at the directory containing the canonical
/// `kzg_bn254_19.srs` so that `gen_srs(K)` reads the SRS used to derive
/// `DARK_DEX_W8_VK_BYTES` in tvm-sdk.
///
/// Usage:
///   PARAMS_DIR=/path/to/tvm-sdk/tvm_vm/halo2_test_data \
///   TVM_SDK_EXPORT_DIR=/path/to/tvm-sdk/tvm_vm/halo2_test_data \
///   cargo test --release test_export_tvm_sdk_data -- --nocapture
///
/// Writes (for N ∈ {num_active_chain_steps} = {0, 1, 2}):
///   {TVM_SDK_EXPORT_DIR}/dark_dex_w8_L{N}_proof.bin
///   {TVM_SDK_EXPORT_DIR}/dark_dex_w8_L{N}_instances.bin   (5 × 32 bytes, LE Fr)
///
/// The live H626 fixture is skipped (different historical window).
#[test]
fn test_export_tvm_sdk_data() {
    use halo2_base::halo2_proofs::plonk::{keygen_pk, keygen_vk};
    use halo2_base::utils::fs::gen_srs;
    use halo2_base::utils::testing::{check_proof_with_instances, gen_proof_with_instances};

    let out_dir = match std::env::var("TVM_SDK_EXPORT_DIR") {
        Ok(p) => std::path::PathBuf::from(p),
        Err(_) => {
            println!("TVM_SDK_EXPORT_DIR not set — skipping.");
            return;
        }
    };
    assert!(out_dir.is_dir(), "TVM_SDK_EXPORT_DIR is not a directory: {}", out_dir.display());

    // Pick only H197 fixtures (the historical-window snapshot the tvm-sdk W=8 tests use).
    let h197: Vec<_> = discover_fixtures()
        .into_iter()
        .filter(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.contains("H197"))
                .unwrap_or(false)
        })
        .collect();
    assert_eq!(h197.len(), 3, "expected 3 H197 fixtures (L0/L1/L2), got {}", h197.len());

    let params = base_circuit_params();
    let ephemeral_pubkey = Fr::from(0xDEADu64);

    // Keygen against the first H197 fixture. VK is shape-only, fixture choice is moot.
    let kg_json = load_fixture(&h197[0]);
    let kg_parsed = parse_fixture(&kg_json);
    let kg_circuit = DarkDexCircuitNew::new(
        kg_parsed.sk_u,
        ephemeral_pubkey,
        kg_parsed.entries,
        kg_parsed.events_proof_siblings,
        kg_parsed.events_proof_position,
        kg_parsed.account_dapp_id,
        kg_parsed.account_id,
        kg_parsed.block_id,
        kg_parsed.envelope_hash_bytes,
        kg_parsed.block_proof_siblings,
        kg_parsed.block_proof_position,
        kg_parsed.dense_chain,
        kg_parsed.num_active_chain_steps,
        params.clone(),
    );

    println!("PARAMS_DIR = {:?}", std::env::var("PARAMS_DIR"));
    println!("Loading SRS (K={})...", K);
    let srs = gen_srs(K);
    let vk = keygen_vk(&srs, &kg_circuit).expect("keygen_vk failed");
    let pk = keygen_pk(&srs, vk, &kg_circuit).expect("keygen_pk failed");
    let break_points = kg_circuit.base_circuit_builder.borrow().break_points();

    for fixture in &h197 {
        let filename = fixture.file_name().unwrap().to_str().unwrap().to_string();
        let json = load_fixture(fixture);
        let parsed = parse_fixture(&json);
        let n_steps = parsed.num_active_chain_steps;
        assert!(n_steps <= 2, "unexpected chain step count {} for fixture {}", n_steps, filename);

        let mut instances = compute_instances(&parsed);
        instances.push(ephemeral_pubkey);
        assert_eq!(instances.len(), 5);

        let prover_circuit = DarkDexCircuitNew::new_for_proving(
            parsed.sk_u,
            ephemeral_pubkey,
            parsed.entries,
            parsed.events_proof_siblings,
            parsed.events_proof_position,
            parsed.account_dapp_id,
            parsed.account_id,
            parsed.block_id,
            parsed.envelope_hash_bytes,
            parsed.block_proof_siblings,
            parsed.block_proof_position,
            parsed.dense_chain,
            parsed.num_active_chain_steps,
            params.clone(),
            break_points.clone(),
        );

        println!("\n[{}] L{}: proving...", filename, n_steps);
        let proof_bytes = gen_proof_with_instances(&srs, &pk, prover_circuit, &[&instances]);
        println!("[{}] proof = {} bytes; sanity-verifying...", filename, proof_bytes.len());
        check_proof_with_instances(&srs, pk.get_vk(), &proof_bytes, &[&instances], true);

        // Serialize each Fr instance as 32 bytes LE (`Fr::to_repr()`), 5 × 32 = 160 B total.
        // The tvm-sdk verifier (`tvm_vm/src/executor/zk_halo2.rs:97-121`) decodes this via
        // `Fr::from_bytes_le()` on the non-u64-shaped path, which is byte-exact symmetric.
        let mut instances_bytes: Vec<u8> = Vec::with_capacity(5 * 32);
        for fr in &instances {
            instances_bytes.extend_from_slice(fr.to_repr().as_ref());
        }
        assert_eq!(instances_bytes.len(), 160);

        let proof_path = out_dir.join(format!("dark_dex_w8_L{}_proof.bin", n_steps));
        let instances_path = out_dir.join(format!("dark_dex_w8_L{}_instances.bin", n_steps));
        std::fs::write(&proof_path, &proof_bytes).expect("write proof");
        std::fs::write(&instances_path, &instances_bytes).expect("write instances");
        println!(
            "[{}] wrote {} ({} B) and {} ({} B)",
            filename,
            proof_path.display(),
            proof_bytes.len(),
            instances_path.display(),
            instances_bytes.len()
        );
    }

    println!("\nDone — wrote 3 fixtures to {}", out_dir.display());
}

#[test]
fn test_focused_l2_h197() {
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/dex_fixture_L2_H197_S1.json");
    if !fixture_path.exists() {
        println!("Fixture not found — skipping.");
        return;
    }

    let json = load_fixture(&fixture_path);
    println!("Description: {}", json.description);
    println!("events_proof depth: {}", json.events_proof_siblings_hex.len());
    println!("block_proof depth: {}", json.block_proof_siblings_hex.len());
    println!("chain_steps: {}", json.num_active_chain_steps);
    println!("chain_len: {}", json.dense_chain.len());

    let parsed = parse_fixture(&json);
    println!("Parsed chain_len: {}", parsed.dense_chain.len());
    for (i, link) in parsed.dense_chain.iter().enumerate() {
        println!("  chain[{}]: active={}, leaf={}, depth={}",
                 i, link.active, hex::encode(&link.leaf_native), link.siblings.len());
    }

    let ephemeral_pubkey = Fr::from(0xDEADu64);
    let mut instances = compute_instances(&parsed);
    instances.push(ephemeral_pubkey);
    println!("Instance 0 (poseidon): {}", hex::encode(instances[0].to_repr()));
    println!("Instance 1 (final_root): {}", hex::encode(instances[1].to_repr()));

    let params = base_circuit_params();
    let circuit = DarkDexCircuitNew::new(
        parsed.sk_u,
        ephemeral_pubkey,
        parsed.entries,
        parsed.events_proof_siblings,
        parsed.events_proof_position,
        parsed.account_dapp_id,
        parsed.account_id,
        parsed.block_id,
        parsed.envelope_hash_bytes,
        parsed.block_proof_siblings,
        parsed.block_proof_position,
        parsed.dense_chain,
        parsed.num_active_chain_steps,
        params,
    );

    println!("Running MockProver with K={}...", K);
    let prover = MockProver::<Fr>::run(K, &circuit, vec![instances]).unwrap();
    match prover.verify() {
        Ok(()) => println!("L2 test PASSED!"),
        Err(errors) => {
            println!("FAILED with {} errors:", errors.len());
            for (i, err) in errors.iter().enumerate() {
                println!("  Error {}: {}", i, err);
            }
            panic!("MockProver failed for L2");
        }
    }
}
