//! Full keygen → prove → verify pipeline using the `gosh-zk-snark-halo2-utils`
//! persistence layer (SRS / VK / PK / config / break_points to disk, three
//! verification strategies).
//!
//! # TODO — replace W=8 fixtures with real live W=128 AN blockchain data
//!
//! Every fixture in `tests/fixtures/` (`dex_fixture_L{0,1,2}_H197_*.json`,
//! `dex_fixture_live_L2_H626_S0.json`) is a legacy `W=8` snapshot — see each
//! file's `description` field. Consequently the `keys/` directory this test
//! populates (`dark_dex_vk.bin`, `dark_dex_pk.bin`, `dark_dex_break_points.bin`,
//! all `dark_dex_all_*.bin` proofs/instances) is W=8 — it does **not** match
//! production tvm-sdk, which pins `HISTORY_PROOF_WINDOW_SIZE = 128`
//! (see `dark_dex_halo2_private_witness_export_lib/src/poseidon.rs`) and
//! whose live verifier consumes `dark_dex_w128_*` artifacts generated by
//! `gosh-dark-dex-halo2-new-circuit::test_export_tvm_sdk_data_w128`.
//!
//! Plan: swap `tests/fixtures/` for real live fixtures captured from the AN
//! blockchain at `HISTORY_PROOF_WINDOW_SIZE = 128`. Once that lands, these
//! tests (and everything they emit into `keys/`) become W=128, matching
//! tvm-sdk and the on-chain verifier.
//!
//! # Running (tests must run sequentially — keygen first, then prove, then verify)
//! ```bash
//! cargo test --test test_dark_dex test_dark_dex_keygen -- --nocapture
//! cargo test --test test_dark_dex test_dark_dex_prove -- --nocapture
//! cargo test --test test_dark_dex test_dark_dex_verify -- --nocapture
//! cargo test --test test_dark_dex test_dark_dex_prove_and_verify_all_fixtures -- --nocapture
//! ```

mod common;

use std::sync::LazyLock;
use std::time::Instant;

use common::{
    base_circuit_params, build_circuit, build_circuit_for_proving, compute_instances,
    discover_fixtures, load_fixture, parse_fixture, K,
};
use gosh_zk_snark_halo2_utils::io::{read_break_points, read_vk, save_break_points};
use gosh_zk_snark_halo2_utils::keygen::generate_and_save_keys;
use gosh_zk_snark_halo2_utils::proof::Proof;
use halo2_base::gates::circuit::BaseCircuitParams;
use halo2_base::halo2_proofs::halo2curves::bn256::{Fr, G1Affine};
use halo2_base::halo2_proofs::halo2curves::ff::PrimeField;
use halo2_base::halo2_proofs::plonk::VerifyingKey;
use halo2_base::utils::fs::gen_srs;

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

fn keys_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("keys")
}

fn saved_config_params() -> BaseCircuitParams {
    let path = keys_dir().join("dark_dex_config_params.json");
    let json = std::fs::read_to_string(&path)
        .expect("dark_dex_config_params.json not found. Run test_dark_dex_keygen first.");
    serde_json::from_str(&json).unwrap()
}

fn read_instances_from_file(path: &std::path::Path) -> Vec<Fr> {
    let bytes = std::fs::read(path).unwrap();
    bytes
        .chunks_exact(32)
        .map(|chunk| {
            let mut repr = <Fr as PrimeField>::Repr::default();
            repr.as_mut().copy_from_slice(chunk);
            Fr::from_repr(repr).expect("invalid Fr encoding in instances file")
        })
        .collect()
}

/// Static VK — deserialized once, reused across tests.
static DARK_DEX_VK: LazyLock<VerifyingKey<G1Affine>> = LazyLock::new(|| {
    let vk_bytes = std::fs::read(keys_dir().join("dark_dex_vk.bin"))
        .expect("dark_dex_vk.bin not found. Run test_dark_dex_keygen first.");
    read_vk(&vk_bytes, &saved_config_params())
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Keygen: load first fixture → build circuit → generate VK/PK → save keys + break_points.
#[test]
fn test_dark_dex_keygen() {
    let t_total = Instant::now();

    let fixtures = discover_fixtures();
    assert!(!fixtures.is_empty(), "No fixture files found");

    let t = Instant::now();
    let json = load_fixture(&fixtures[0]);
    let parsed = parse_fixture(&json);
    println!("[timing] fixture load + parse: {:?}", t.elapsed());

    let t = Instant::now();
    let params = base_circuit_params();
    let circuit = build_circuit(parsed, params.clone());
    println!("[timing] circuit construction: {:?}", t.elapsed());

    let t = Instant::now();
    let srs = gen_srs(K);
    println!("[timing] SRS generation: {:?}", t.elapsed());

    let keys_dir = keys_dir();
    std::fs::create_dir_all(&keys_dir).unwrap();
    let vk_path = keys_dir.join("dark_dex_vk.bin");
    let pk_path = keys_dir.join("dark_dex_pk.bin");
    let config_path = keys_dir.join("dark_dex_config_params.json");
    let bp_path = keys_dir.join("dark_dex_break_points.bin");

    let t = Instant::now();
    generate_and_save_keys(
        &srs,
        &circuit,
        &params,
        vk_path.to_str().unwrap(),
        pk_path.to_str().unwrap(),
        config_path.to_str().unwrap(),
    );
    println!("[timing] keygen + save: {:?}", t.elapsed());

    let break_points = circuit.base_circuit_builder.borrow().break_points();
    save_break_points(&break_points, bp_path.to_str().unwrap());
    println!(
        "break_points saved: {} phases, {} total points",
        break_points.len(),
        break_points.iter().map(|v| v.len()).sum::<usize>()
    );

    println!("[timing] TOTAL: {:?}", t_total.elapsed());
}

/// Prove first fixture → save proof + instances → verify + negative test.
///
/// Requires `test_dark_dex_keygen` to have run first.
#[test]
fn test_dark_dex_prove() {
    let t_total = Instant::now();

    let fixtures = discover_fixtures();
    assert!(!fixtures.is_empty(), "No fixture files found");

    let keys_dir = keys_dir();
    let pk_path = keys_dir.join("dark_dex_pk.bin");
    let vk_path = keys_dir.join("dark_dex_vk.bin");
    let config_path = keys_dir.join("dark_dex_config_params.json");
    let bp_path = keys_dir.join("dark_dex_break_points.bin");

    assert!(
        pk_path.exists() && config_path.exists() && bp_path.exists(),
        "Key files not found. Run test_dark_dex_keygen first."
    );

    let json = load_fixture(&fixtures[0]);
    let parsed = parse_fixture(&json);
    let instances = compute_instances(&parsed);

    let config_params = saved_config_params();
    let break_points = read_break_points(bp_path.to_str().unwrap());
    let prove_circuit = build_circuit_for_proving(parsed, config_params, break_points);

    let srs = gen_srs(K);

    let t = Instant::now();
    let proof = Proof::create_for_circuit_from_paths(
        &srs,
        pk_path.to_str().unwrap(),
        config_path.to_str().unwrap(),
        prove_circuit,
        &[&instances],
    );
    println!("[timing] proof generation: {:?}", t.elapsed());
    println!("proof size: {} bytes", proof.as_bytes().len());

    let proof_path = keys_dir.join("dark_dex_proof.bin");
    let instances_path = keys_dir.join("dark_dex_instances.bin");
    std::fs::write(&proof_path, proof.as_bytes()).unwrap();
    let instances_bytes: Vec<u8> = instances
        .iter()
        .flat_map(|f| f.to_repr().as_ref().to_vec())
        .collect();
    std::fs::write(&instances_path, &instances_bytes).unwrap();

    // Positive verification.
    let valid = proof.verify_with_vk_from_path(
        vk_path.to_str().unwrap(),
        &srs,
        config_path.to_str().unwrap(),
        &[&instances],
    );
    assert!(valid, "Proof verification should pass with correct instances");

    // Negative verification.
    let wrong = vec![Fr::from(42u64); 5];
    assert!(
        !proof.verify_with_vk_from_path(
            vk_path.to_str().unwrap(),
            &srs,
            config_path.to_str().unwrap(),
            &[&wrong],
        ),
        "Proof verification should fail with wrong instances"
    );

    println!("[timing] TOTAL: {:?}", t_total.elapsed());
}

/// Verify a previously saved proof using each of the three VK strategies.
///
/// Requires `test_dark_dex_prove` to have run first.
#[test]
fn test_dark_dex_verify() {
    let keys_dir = keys_dir();
    let vk_path = keys_dir.join("dark_dex_vk.bin");
    let proof_path = keys_dir.join("dark_dex_proof.bin");
    let config_path = keys_dir.join("dark_dex_config_params.json");
    let instances_path = keys_dir.join("dark_dex_instances.bin");

    assert!(
        vk_path.exists() && proof_path.exists() && config_path.exists() && instances_path.exists(),
        "Key/proof/instances files not found. Run test_dark_dex_prove first."
    );

    let proof = Proof::new(std::fs::read(&proof_path).unwrap());
    let instances = read_instances_from_file(&instances_path);
    let srs = gen_srs(K);

    // Strategy 1: VK from file path.
    let t = Instant::now();
    let valid = proof.verify_with_vk_from_path(
        vk_path.to_str().unwrap(),
        &srs,
        config_path.to_str().unwrap(),
        &[&instances],
    );
    println!("[timing] verify (VK from file): {:?}", t.elapsed());
    assert!(valid, "verify with VK from file failed");

    // Strategy 2: VK deserialized from raw bytes each call.
    let t = Instant::now();
    let vk_bytes = std::fs::read(&vk_path).unwrap();
    let config_params = saved_config_params();
    let valid = proof.verify_with_vk_from_bytes(&vk_bytes, &srs, &config_params, &[&instances]);
    println!("[timing] verify (VK from bytes): {:?}", t.elapsed());
    assert!(valid, "verify with VK from bytes failed");

    // Strategy 3: static VK (LazyLock).
    let t = Instant::now();
    let vk: &VerifyingKey<G1Affine> = &DARK_DEX_VK;
    println!("[timing] VK LazyLock init: {:?}", t.elapsed());
    let t = Instant::now();
    let valid = proof.verify_with_vk(vk, &srs, &[&instances]);
    println!("[timing] verify (static VK): {:?}", t.elapsed());
    assert!(valid, "verify with static VK failed");
}

/// Prove and verify all fixtures with a shared VK/PK.
///
/// Requires `test_dark_dex_keygen` to have run first.
#[test]
fn test_dark_dex_prove_and_verify_all_fixtures() {
    let t_total = Instant::now();

    let fixtures = discover_fixtures();
    assert!(!fixtures.is_empty(), "No fixture files found");
    println!("Found {} fixture(s)", fixtures.len());

    let keys_dir = keys_dir();
    let pk_path = keys_dir.join("dark_dex_pk.bin");
    let vk_path = keys_dir.join("dark_dex_vk.bin");
    let config_path = keys_dir.join("dark_dex_config_params.json");
    let bp_path = keys_dir.join("dark_dex_break_points.bin");

    assert!(
        pk_path.exists() && config_path.exists() && bp_path.exists(),
        "Key files not found. Run test_dark_dex_keygen first."
    );

    let srs = gen_srs(K);
    let config_params = saved_config_params();
    let saved_break_points = read_break_points(bp_path.to_str().unwrap());

    struct ProofResult {
        filename: String,
        chain_steps: usize,
        prove_ms: u128,
        verify_ms: u128,
        proof_size: usize,
    }
    let mut results: Vec<ProofResult> = Vec::new();

    for fixture_path in &fixtures {
        let filename = fixture_path.file_name().unwrap().to_str().unwrap().to_string();
        let stem = fixture_path.file_stem().unwrap().to_str().unwrap().to_string();
        println!("\n========== {} ==========", filename);

        let json = load_fixture(fixture_path);
        let chain_steps = json.num_active_chain_steps;
        println!("  chain_steps: {}", chain_steps);

        let parsed = parse_fixture(&json);
        let instances = compute_instances(&parsed);

        let prove_circuit =
            build_circuit_for_proving(parsed, config_params.clone(), saved_break_points.clone());

        let t = Instant::now();
        let proof = Proof::create_for_circuit_from_paths(
            &srs,
            pk_path.to_str().unwrap(),
            config_path.to_str().unwrap(),
            prove_circuit,
            &[&instances],
        );
        let prove_ms = t.elapsed().as_millis();
        println!("  proof generation: {}ms ({} bytes)", prove_ms, proof.as_bytes().len());

        std::fs::write(
            keys_dir.join(format!("dark_dex_all_{}_proof.bin", stem)),
            proof.as_bytes(),
        )
        .unwrap();
        let instances_bytes: Vec<u8> = instances
            .iter()
            .flat_map(|f| f.to_repr().as_ref().to_vec())
            .collect();
        std::fs::write(
            keys_dir.join(format!("dark_dex_all_{}_instances.bin", stem)),
            &instances_bytes,
        )
        .unwrap();

        // Verify with all three strategies.
        let t = Instant::now();
        let valid = proof.verify_with_vk_from_path(
            vk_path.to_str().unwrap(),
            &srs,
            config_path.to_str().unwrap(),
            &[&instances],
        );
        let verify_ms = t.elapsed().as_millis();
        assert!(valid, "VK-from-path verification failed for {}", filename);

        let vk_bytes = std::fs::read(&vk_path).unwrap();
        assert!(
            proof.verify_with_vk_from_bytes(&vk_bytes, &srs, &config_params, &[&instances]),
            "VK-from-bytes verification failed for {}",
            filename
        );

        assert!(
            proof.verify_with_vk(&DARK_DEX_VK, &srs, &[&instances]),
            "static-VK verification failed for {}",
            filename
        );

        println!("  {} PASSED (all 3 verification strategies)", filename);

        results.push(ProofResult {
            filename,
            chain_steps,
            prove_ms,
            verify_ms,
            proof_size: proof.as_bytes().len(),
        });
    }

    println!("\n╔════════════════════════════════════════════╤════════╤══════════╤══════════╤════════════╗");
    println!("║ fixture                                    │ steps  │  prove   │  verify  │ proof_size ║");
    println!("╠════════════════════════════════════════════╪════════╪══════════╪══════════╪════════════╣");
    for r in &results {
        println!(
            "║ {:<42} │   {:>2}   │ {:>6}ms │ {:>6}ms │   {:>6}B  ║",
            r.filename, r.chain_steps, r.prove_ms, r.verify_ms, r.proof_size,
        );
    }
    println!("╚════════════════════════════════════════════╧════════╧══════════╧══════════╧════════════╝");
    println!("\nAll {} fixture(s) passed with shared VK/PK!", results.len());
    println!("[timing] TOTAL: {:?}", t_total.elapsed());
}
